name: "✅ Feature"
description: "Feature 작업 사항을 입력해주세요."
title: "[Feature]: "
labels: "enhancement"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: 이슈에 대한 설명 
      placeholder: 이슈에 대한 설명
    validations:
      required: true
  - type: textarea
    id: todos
    attributes:
      label: Todos
      description: Todo list 추가
      value: "- [ ] todo1"
    validations:
      required: true
  - type: textarea
    id: etc
    attributes:
      label: ETC
      description: 기타 이슈사항
